/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings src/worker-configuration.d.ts` (hash: 1d52bbbfce17e3b9493a60e100f6182c)
interface __BaseEnv_CloudflareBindings {
	OAUTH_KV: KVNamespace;
	DB: D1Database;
	PUBLIC_BASE_URL: string;
	ACCESS_CLIENT_ID: string;
	ACCESS_AUTHORIZATION_URL: string;
	ACCESS_TOKEN_URL: string;
	ACCESS_JWKS_URL: string;
	ACCESS_ISSUER: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_BASE_URL" | "ACCESS_CLIENT_ID" | "ACCESS_AUTHORIZATION_URL" | "ACCESS_TOKEN_URL" | "ACCESS_JWKS_URL" | "ACCESS_ISSUER">> {}
}
